apiVersion: v1
kind: Pod
metadata:
  name: minikube
spec:
  containers:
    - name: minikube
      image: minikube:latest
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "200Mi"
